/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.main.program;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ujang
 */
public class Transaction extends javax.swing.JFrame {
    
    ArrayList<String> prices = new ArrayList<>();
    
    public void reset_transaction(){
        InputName.setText(null);
        InputQty.setText("1");
        InputGrandTotal.setText("0");
        DefaultTableModel model = (DefaultTableModel) TableList.getModel();
        model.setRowCount(0);
    }
    
    public void show_combobox(){
        try {
            String sql = "SELECT * FROM cd_music";
            java.sql.Connection conn    = (Connection)Config.configDB();
            java.sql.Statement stm      = conn.createStatement();
            java.sql.ResultSet res      = stm.executeQuery(sql);
            
            while(res.next()){
                if(res.getRow() == 1){
                    DisplayPrice.setText(res.getString(4));
                }
                ComboboxMusic.addItem(res.getString(2));
                prices.add(res.getString(4));
            }
            
            res.last();
            int totalRow = res.getRow();
            res.first();
            
        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }

    /**
     * Creates new form Transaction
     */
    public Transaction() {
        initComponents();
        show_combobox();
        setResizable(false);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTransaction = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        TitleTransaction = new javax.swing.JLabel();
        PanelForm = new javax.swing.JPanel();
        ComboboxMusic = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InputName = new javax.swing.JTextField();
        InputQty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableList = new javax.swing.JTable();
        SaveTransaction = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DisplayPrice = new javax.swing.JTextField();
        BtnAddList = new javax.swing.JButton();
        InputGrandTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        TitleTransaction.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TitleTransaction.setText("Menu Transaksi");

        PanelForm.setBackground(new java.awt.Color(204, 204, 204));

        ComboboxMusic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboboxMusic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboboxMusicItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Form Transaksi");

        jLabel2.setText("Nama Pembeli");

        jLabel3.setText("Pilih Lagu");

        jLabel4.setText("Jumlah");

        InputQty.setText("1");

        TableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Judul", "Jumlah", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableList.setRowHeight(20);
        jScrollPane1.setViewportView(TableList);

        SaveTransaction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SaveTransaction.setText("Tambah Transaksi");
        SaveTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveTransactionActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga");

        DisplayPrice.setEditable(false);
        DisplayPrice.setText("0");
        DisplayPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayPriceActionPerformed(evt);
            }
        });

        BtnAddList.setText("Tambah");
        BtnAddList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddListActionPerformed(evt);
            }
        });

        InputGrandTotal.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Grandtotal");

        javax.swing.GroupLayout PanelFormLayout = new javax.swing.GroupLayout(PanelForm);
        PanelForm.setLayout(PanelFormLayout);
        PanelFormLayout.setHorizontalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputQty)
                            .addComponent(InputName)
                            .addComponent(DisplayPrice)
                            .addComponent(ComboboxMusic, 0, 302, Short.MAX_VALUE)))
                    .addComponent(BtnAddList))
                .addGap(70, 70, 70)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SaveTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InputGrandTotal)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelFormLayout.setVerticalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(PanelFormLayout.createSequentialGroup()
                                .addComponent(InputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboboxMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addGap(17, 17, 17)
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(InputQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(DisplayPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BtnAddList))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(SaveTransaction)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout PanelTransactionLayout = new javax.swing.GroupLayout(PanelTransaction);
        PanelTransaction.setLayout(PanelTransactionLayout);
        PanelTransactionLayout.setHorizontalGroup(
            PanelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTransactionLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(TitleTransaction)
                .addContainerGap(295, Short.MAX_VALUE))
            .addComponent(PanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelTransactionLayout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelTransactionLayout.setVerticalGroup(
            PanelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTransactionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(33, 33, 33)
                .addComponent(TitleTransaction)
                .addGap(39, 39, 39)
                .addComponent(PanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new MainMenu().show();
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void DisplayPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayPriceActionPerformed

    private void ComboboxMusicItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboboxMusicItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            Object item = evt.getItem();
            int index = ComboboxMusic.getSelectedIndex();
            if(!prices.isEmpty()){
                DisplayPrice.setText(prices.get(index));
            }
        }
    }//GEN-LAST:event_ComboboxMusicItemStateChanged

    private void BtnAddListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddListActionPerformed
        
        String no       = Integer.toString(TableList.getRowCount() + 1);
        String judul    = (String) ComboboxMusic.getSelectedItem();
        String jumlah   = InputQty.getText();
        String price    = DisplayPrice.getText();
        
        int calculate   = Integer.parseInt(jumlah) * Integer.parseInt(price);
        String subtotal = Integer.toString(calculate);
        String[] data = {
            no, judul, jumlah, subtotal
        };
                
        DefaultTableModel model = (DefaultTableModel)TableList.getModel();
        model.addRow(data);
        
        int grandtotal = 0;
        for (int i=0; i<TableList.getRowCount(); i++) 
        {
            String subtotalTbl = TableList.getValueAt(i, 3).toString();
            grandtotal += Integer.parseInt(subtotalTbl);
        }
        InputGrandTotal.setText(Integer.toString(grandtotal));
    }//GEN-LAST:event_BtnAddListActionPerformed

    private void SaveTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveTransactionActionPerformed
        
        String name = InputName.getText();
        int grandtotal = 0;
        String items = "";
        Date date = new Date();
        SimpleDateFormat sdfDate = new SimpleDateFormat ("yyyy-MM-dd");

        for (int i=0; i<TableList.getRowCount(); i++) 
        {
            String no           = TableList.getValueAt(i, 0).toString();
            String title        = TableList.getValueAt(i, 1).toString();
            String qty          = TableList.getValueAt(i, 2).toString();
            String subtotal     = TableList.getValueAt(i, 3).toString();
            grandtotal += Integer.parseInt(subtotal);
            
            items += "No:"+no+" | Judul:"+title+" | Jumlah:"+qty+" | Subtotal:"+subtotal+" <br> ";
        }
        
        try {
            if(!name.isEmpty() && grandtotal > 0){
                String sql = "INSERT INTO transaction SET name='"+name+"', items='"+items+"', grand_total='"+grandtotal+"', date='"+sdfDate.format(date)+"'";
                java.sql.Connection conn    = (Connection)Config.configDB();
                java.sql.Statement stm      = conn.createStatement();
                int id = stm.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
                
                JOptionPane.showMessageDialog(null, "Transaksi berhasil ditambahkan..!");
                System.out.println(id);
                reset_transaction();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_SaveTransactionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddList;
    private javax.swing.JComboBox ComboboxMusic;
    private javax.swing.JTextField DisplayPrice;
    private javax.swing.JTextField InputGrandTotal;
    private javax.swing.JTextField InputName;
    private javax.swing.JTextField InputQty;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JPanel PanelTransaction;
    private javax.swing.JButton SaveTransaction;
    private javax.swing.JTable TableList;
    private javax.swing.JLabel TitleTransaction;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
